package local.kapinos.common.persistence;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

@Entity
@Table(name = "books")
@EntityListeners(BookCallbackListener.class)
public class Book implements Serializable {

	private static final long serialVersionUID = 1L;

	// mark id as primary key with autogenerated value
	// map database column id with id field
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private int id;
	private String name;

	@Embedded
	@AttributeOverrides({
		@AttributeOverride(name = "name", column = @Column(name = "PUBLISHER")),
	    @AttributeOverride(name = "address", column = @Column(name = "PUBLISHER_ADDRESS"))})
	private Publisher publisher;
	
	@Lob @Basic(fetch= FetchType.EAGER)
	private byte[] image;
	
	@Lob @Basic(fetch= FetchType.EAGER)
	private String lob_xml;
	
	public Book() {
	}

	public Book(String name) {
		this.name = name;
		this.publisher = new Publisher("unknown name", "aunknown address");
		try {
			this.image = "test data".getBytes("UTF-8");
			this.lob_xml = "<tag>test data<tag>";
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Publisher getPublisher() {
		return publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	public byte[] getImage() {
		return image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getLobXml() {
		return lob_xml;
	}

	public void setLobXml(String lob_xml) {
		this.lob_xml = lob_xml;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}
}